version: '3'

services:

  build:
    image: mahmedtech/stm32-cubeide-headless:latest
    build: ./CI
    volumes:
      - ".:/workspace/Multichannel-Temperature-Control"
    command:
      [
        "/bin/bash",
        "-c",
        "/workspace/Multichannel-Temperature-Control/builder.sh"
      ]
