# declarations to build/run local image used for local development and testing
# except for the image name, everything should be the same as in docker-compose-ghcr.yml (so that the image is built in the same way both in production and locally, to ease testing)

version: '3'

services:

  build:
    image: niuslar/stm32-cubeide-headless:local
    build: ./CI
    volumes:
      - ".:/workspace/Multichannel-Temperature-Control"
    command:
      [
        "/bin/bash",
        "-c",
        "/workspace/Multichannel-Temperature-Control/builder.sh"
      ]
