name: C/C++ CI

on: push
 #   branches: [ develop ]
 # pull_request:
 #   branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: mahmedtech/stm32-cubeide-headless:latest
    steps:
    - uses: actions/checkout@v3
    - name: build 1
      run:
        stm32cubeide --launcher.suppressErrors -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild "$@" \
        -data /workspace -import /__w/Multichannel-Temperature-Control/Multichannel-Temperature-Control -cleanBuild 'Multichannel temperature sensor' -markerType cdt \
        || { echo "Build Failed"; exit 1; }
 #     run: chmod +x /__w/Multichannel-Temperature-Control/Multichannel-Temperature-Control/builder.sh
 #   - name: build 2
  #    run: ./workspace/Multichannel-Temperature-Control/builder.sh
