name: STM32 C/C++ CI

on: push
 #   branches: [ develop ]
 # pull_request:
 #   branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: mahmedtech/stm32-cubeide-headless:latest
    steps:
    - uses: actions/checkout@v3
    - name: build App
      run: |
        chmod +x /opt/st/stm32cubeide_1.9.0/headless-build.sh
        cd /opt/st/stm32cubeide_1.9.0
        ./headless-build.sh -data /workspace -import /__w/Multichannel-Temperature-Control/Multichannel-Temperature-Control -cleanBuild 'Multichannel temperature sensor' -markerType cdt || { echo "Build Failed"; exit 1; }
