name: C/C++ CI

on: push
 #   branches: [ develop ]
 # pull_request:
 #   branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: mahmedtech/stm32-cubeide-headless:latest
    steps:
    - uses: actions/checkout@v3
    - name: build 1
      run:
        pwd
        ls 
 #     run: chmod +x /workspace/Multichannel-Temperature-Control/builder.sh
 #   - name: build 2
  #    run: ./workspace/Multichannel-Temperature-Control/builder.sh
