name: STM32 C/C++ CI

on: push
 #   branches: [ develop ]
 # pull_request:
 #   branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: mahmedtech/stm32-cubeide-headless:latest
    steps:
    - uses: actions/checkout@v3
    - name: build 0 
      run: |
        echo ${{ github.workspace }}
        ls -la 
        ls -la /opt/st/stm32cubeide_1.9.0
    - name: build 1
      run: |
        chmod +x /opt/st/stm32cubeide_1.9.0/headless-build.sh
        cd /opt/st/stm32cubeide_1.9.0
        ./headless-build.sh -data /workspace -import ${{ github.workspace }} -cleanBuild 'Multichannel temperature sensor' -markerType cdt || { echo "Build Failed"; exit 1; }
#    - name: build 2
#      run: ./opt/st/stm32cubeide_1.9.0/headless-build.sh
      #-data /workspace -import /__w/Multichannel-Temperature-Control/Multichannel-Temperature-Control -cleanBuild 'Multichannel temperature sensor' -markerType cdt || { echo "Build Failed"; exit 1; }
 #       cat /opt/st/stm32cubeide_1.9.0/headless-build.sh
 #     run: chmod +x /__w/Multichannel-Temperature-Control/Multichannel-Temperature-Control/builder.sh
 #   - name: build 2
  #    run: ./workspace/Multichannel-Temperature-Control/builder.sh
